version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

  agent_a:
    build:
      context: ./Backend
      dockerfile: Dockerfile.agent_a
    ports:
      - '8000:8000'
    depends_on:
      - prometheus

  agent_b:
    build:
      context: ./Backend
      dockerfile: Dockerfile.agent_b
    ports:
      - '8001:8001'
    depends_on:
      - prometheus

volumes:
  grafana-storage:
